# -*- coding: utf-8 -*-
"""case_study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fJOo7cSfLHIvTO9WLO3fb1yJtevMyhnU
"""

pip install torch torchvision matplotlib numpy

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import numpy as np
import matplotlib.pyplot as plt

class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = nn.Parameter(torch.empty(out_features, in_features))
        self.bias = nn.Parameter(torch.zeros(out_features))
        self.gate_scores = nn.Parameter(torch.zeros(out_features, in_features))
        nn.init.kaiming_uniform_(self.weight, a=0.01)

    def forward(self, x):
        gates = torch.sigmoid(self.gate_scores * 7)
        return x @ (self.weight * gates).T + self.bias

    def gate_values(self):
        return torch.sigmoid(self.gate_scores * 7).detach()

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = PrunableLinear(3072, 1024)
        self.fc2 = PrunableLinear(1024, 512)
        self.fc3 = PrunableLinear(512, 256)
        self.fc4 = PrunableLinear(256, 10)
        self.relu = nn.ReLU()
        self.bn1 = nn.BatchNorm1d(1024)
        self.bn2 = nn.BatchNorm1d(512)
        self.bn3 = nn.BatchNorm1d(256)

    def forward(self, x):
        x = x.view(-1, 3072)
        x = self.relu(self.bn1(self.fc1(x)))
        x = self.relu(self.bn2(self.fc2(x)))
        x = self.relu(self.bn3(self.fc3(x)))
        return self.fc4(x)

    def all_gates(self):
        return torch.cat([
            self.fc1.gate_values().flatten(),
            self.fc2.gate_values().flatten(),
            self.fc3.gate_values().flatten(),
            self.fc4.gate_values().flatten()
        ])

    def sparsity_loss(self):
        gates = torch.cat([
            torch.sigmoid(self.fc1.gate_scores * 7).flatten(),
            torch.sigmoid(self.fc2.gate_scores * 7).flatten(),
            torch.sigmoid(self.fc3.gate_scores * 7).flatten(),
            torch.sigmoid(self.fc4.gate_scores * 7).flatten()
        ])
        return gates.sum()

    def sparsity(self):
        g = self.all_gates()
        return (g < 1e-2).float().mean().item()

def get_data():
    transform = transforms.Compose([
        transforms.RandomHorizontalFlip(),
        transforms.RandomCrop(32, padding=4),
        transforms.ToTensor(),
        transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))
    ])
    train = datasets.CIFAR10("./data", train=True, download=True, transform=transform)
    test = datasets.CIFAR10("./data", train=False, download=True, transform=transform)
    return DataLoader(train, batch_size=256, shuffle=True), DataLoader(test, batch_size=256)

def train_epoch(model, loader, opt, lam, device, epoch):
    model.train()
    ce_fn = nn.CrossEntropyLoss()
    total = correct = 0

    for x,y in loader:
        x,y = x.to(device), y.to(device)
        out = model(x)
        ce = ce_fn(out,y)
        sp = model.sparsity_loss()

        if epoch < 5:
            loss = ce
        else:
            loss = ce + lam * sp

        opt.zero_grad()
        loss.backward()
        opt.step()

        correct += (out.argmax(1)==y).sum().item()
        total += len(y)

    return correct/total

@torch.no_grad()
def eval_model(model, loader, device):
    model.eval()
    correct = total = 0
    for x,y in loader:
        x,y = x.to(device), y.to(device)
        out = model(x)
        correct += (out.argmax(1)==y).sum().item()
        total += len(y)
    return correct/total

def run(lam):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    train_loader, test_loader = get_data()
    model = Net().to(device)
    opt = optim.Adam(model.parameters(), lr=1e-3)

    for epoch in range(1,21):
        train_acc = train_epoch(model, train_loader, opt, lam, device, epoch)
        test_acc = eval_model(model, test_loader, device)
        sp = model.sparsity()
        print(f"Epoch {epoch:02d} | train {train_acc:.3f} | test {test_acc:.3f} | sparsity {sp:.3f}")

    return model

if __name__ == "__main__":
    for lam in [1e-6, 5e-6, 1e-5]:
        print(f"\nLAMBDA = {lam}")
        run(lam)

def run(lam):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    train_loader, test_loader = get_data()

    model = Net().to(device)
    opt = torch.optim.Adam(model.parameters(), lr=1e-3)

    history = []

    for epoch in range(1, 21):
        train_acc = train_epoch(model, train_loader, opt, lam, device, epoch)
        test_acc = eval_model(model, test_loader, device)
        sp = model.sparsity()

        history.append((epoch, train_acc, test_acc, sp))

        print(f"Epoch {epoch:02d} | train {train_acc:.3f} | test {test_acc:.3f} | sparsity {sp:.3f}")

    return {
        "lambda": lam,
        "final_acc": test_acc,
        "final_sp": sp,
        "gate_vals": model.all_gates().cpu().numpy(),
        "history": history
    }

def plot_all(results):
    import matplotlib.pyplot as plt

    lambdas = [r["lambda"] for r in results]
    accs = [r["final_acc"] for r in results]
    sparsities = [r["final_sp"] for r in results]

    plt.figure()
    plt.plot(sparsities, accs, marker='o')
    for i, lam in enumerate(lambdas):
        plt.text(sparsities[i], accs[i], f"λ={lam}")
    plt.xlabel("Sparsity")
    plt.ylabel("Accuracy")
    plt.title("Accuracy vs Sparsity")
    plt.grid()
    plt.show()

    plt.figure()
    x = range(len(lambdas))
    plt.bar(x, accs, width=0.4, label="Accuracy")
    plt.bar([i+0.4 for i in x], sparsities, width=0.4, label="Sparsity")
    plt.xticks([i+0.2 for i in x], [str(l) for l in lambdas])
    plt.legend()
    plt.title("Accuracy & Sparsity vs Lambda")
    plt.show()

    plt.figure()
    for r in results:
        plt.hist(r["gate_vals"], bins=80, alpha=0.5, label=f"λ={r['lambda']}")
    plt.axvline(x=1e-2)
    plt.legend()
    plt.title("Gate Value Distribution")
    plt.show()

    plt.figure()
    for r in results:
        epochs = [h[0] for h in r["history"]]
        test_acc = [h[2] for h in r["history"]]
        plt.plot(epochs, test_acc, marker='o', label=f"λ={r['lambda']}")
    plt.xlabel("Epoch")
    plt.ylabel("Test Accuracy")
    plt.legend()
    plt.title("Test Accuracy vs Epoch")
    plt.grid()
    plt.show()

if __name__ == "__main__":
    results = []

    for lam in [1e-6, 5e-6, 1e-5]:
        print(f"\nLAMBDA = {lam}")
        r = run(lam)
        results.append(r)

    plot_all(results)

